# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: ML-KEM
type: kem
implementations:
  - name: ML-KEM-512
    claimed-nist-level: 1
    claimed-security: IND-CCA2
    length-public-key: 800
    length-ciphertext: 768
    length-secret-key: 1632
    length-shared-secret: 32
    kat-sha256: cc398096eee868ea6164b5f51e9a751da65d8ed44e636b09573ed57bc50ac4ed
  - name: ML-KEM-768
    claimed-nist-level: 3
    claimed-security: IND-CCA2
    length-public-key: 1184
    length-ciphertext: 1088
    length-secret-key: 2400
    length-shared-secret: 32
    kat-sha256: b328a57e85808d78766d994f17c9d85a2e554b80a6a16fb8c099534353350551
  - name: ML-KEM-1024
    claimed-nist-level: 5
    claimed-security: IND-CCA2
    length-public-key: 1568
    length-ciphertext: 1568
    length-secret-key: 3168
    length-shared-secret: 32
    kat-sha256: 8854d2ee93e01d07dd91807fb033194f08decde49fffc5a56e38fc41f984330f
