# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: Dependencies (yum)
description: Install dependencies via yum

inputs:
  packages:
    description: Space-separated list of additional packages to install
    required: false
    default: ''
  sudo:
    required: false
    default: 'sudo'

runs:
  using: composite
  steps:
    - name: Install base packages
      shell: bash
      run: |
        ${{ inputs.sudo }} yum install make gcc python3 git -y
    - name: Install additional packages
      if: ${{ inputs.packages != ''}}
      shell: bash
      run: |
        ${{ inputs.sudo }} yum install ${{ inputs.packages }} -y
