# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: Bench (Ubuntu PMU 512)

on:
  push:

permissions:
  contents: read

jobs:
  bench-pmu-512:
    name: Ubuntu PMU ML-KEM-512
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3

      - name: Build ML-KEM-512 benchmark (optimized)
        run: make bench_512 CYCLES=PMU OPT=1 -j"$(nproc)"

      - name: Run ML-KEM-512 benchmark (capture output)
        run: |
          make run_bench_512 CYCLES=PMU | tee bench_512.txt

      - name: Extract bench.json
        run: |
          python3 - <<'PY'
          import re, json
          txt = open('bench_512.txt','r',encoding='utf-8',errors='ignore').read()
          m = dict(re.findall(r'(keypair cycles|encaps cycles|decaps cycles)\s*=\s*(\d+)', txt))
          order = [
              ('keypair cycles','ML-KEM-512 keypair'),
              ('encaps cycles','ML-KEM-512 encaps'),
              ('decaps cycles','ML-KEM-512 decaps'),
          ]
          out = [
            {'name': name, 'unit': 'cycles', 'value': int(m[k])}
            for k, name in order if k in m
          ]
          if not out:
            raise SystemExit('No cycle results found in bench_512.txt')
          open('bench.json','w').write(json.dumps(out))
          PY

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bench-pmu-512
          path: |
            bench_512.txt
            bench.json
